### ISSUE TITLE
S3 PreSigned Url 도입

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/KOIN_API#284]
### 요약

![image](https://github.com/BCSDLab/KOIN_API/assets/71889359/a5f8e2e6-26e7-4024-8a8f-6e8b4cda28e3)

에서

![image](https://github.com/BCSDLab/KOIN_API/assets/71889359/574f328a-de4e-41c0-ac36-341712527259)
(PreSigned Url을 통한 파일 업로드 프로세스)

로 변경하여 서버가 아닌 저장소에 직접 파일 업로드할 수 있도록 수정

### 상세 설명
일반적으로 S3를 사용하는 웹 어플리케이션들은 아래와 같은 방식으로 파일을 업로드하였다.

![image](https://github.com/BCSDLab/KOIN_API/assets/71889359/a5f8e2e6-26e7-4024-8a8f-6e8b4cda28e3)
(일반적인[multipart/form-data를 통한] 파일 업로드 프로세스)

이 때 (1) 과정에서 용량이 큰 파일을 보내게 된다면 이는 성능에 악영향을 미친다. (서버의 자원을 많이 사용하기도 하고, HTTP에서 큰 파일을 여러 번의 작은 요청으로 분할하여 보내게 되어 성능이 떨어진다.)
이러한 성능 문제를 해결하기 위해 S3에서 제공하는 방법이 PreSigned Url이다.
PreSigned Url은 이름 그대로 미리 서명한 Url이라는 뜻이다. S3의 소유자가 미리 특정 권한(파일 업로드, 파일 다운로드 등)에 대해 서명을 해준 뒤 사용자에게 해당 Url을 제공해준다. 사용자는 서명된 권한을 사용할 수 있다. 소유자가 여러 정보에 대해 미리 서명을 해두고, 사용자가 추후에 전달받아 사용한다는 점에서 수표와 비슷하다.
PreSigned Url을 사용하게 된다면, 클라이언트가 서버에 거치지 않고 파일을 저장소에 직접 업로드할 수 있어, 서버의 자원을 절약할 수 있다.
동작 과정은 아래와 같다.

![image](https://github.com/BCSDLab/KOIN_API/assets/71889359/574f328a-de4e-41c0-ac36-341712527259)
(PreSigned Url을 통한 파일 업로드 프로세스)

위와 같이 동작하며, 기존과 달리 클라이언트에서 직접 저장소로 파일을 업로드한다. 6번 이후 동작과정은 기존과 동일하게, API의 요청의 필드로 여러 데이터들과 함께 파일 저장 경로를 넘겨주면 된다.

- 상세 참고: [구글 문서](https://docs.google.com/document/d/10ojk_UGedrI2LMxoit1Hz4BkwHll4ZtbTgdZF25DutU/edit#heading=h.5xf6ghadnplu) 
(or [블로깅 내용](https://velog.io/@invidam/S3-Presigned-Url-%EB%8F%84%EC%9E%85%ED%95%98%EA%B8%B0))

## Task List

- [ ] PreSigned Url 위한 설정
- [ ] PreSigned Url 생성
- [ ] PreSigned Url 문서 작성
- [ ] PreSigned Url HTTPS 추가
- [ ] PreSigned Url CNAME 적용하여 s3 경로 숨기기
