### ISSUE TITLE
HTTP 로깅을 추가한다.

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/KOIN_API#348]
### as-is
- HTTP 로깅이 없어, 오류 확인에 어려움이 있었다.
### to-be
- 파일단위로 HTTP 로깅 추가
## Task List

- [x] resources/ 경로에 로깅 위한 코드 추가
- [x] 톰캣 설정 변경해 로깅 출력(파일로)
- [x] (추후) 파일보다 더 좋은 방식으로 출력
